### ISSUE TITLE
Unable to configure pylint-django with django-configurations

### ISSUE THREAD

**Issue by madmatah** [PyCQA/pylint-django#307] opened 2021-01-19 17:12 UTC
Hello,

I'm working on a django project that uses [django-configurations](https://github.com/jazzband/django-configurations) to manage its settings. I'm upgrading `pylint-django` from version `2.3.0` to `2.4.2` and i'm stuck with the _django-not-configured_ error.

I can't find a way to configure django in pylint-django's context using django-configurations.
Do you know a way to solve this kind of problem that I would have missed ?

Here is a `pip freeze` output : 

```
$ pip freeze | grep -i -e pylint -e django
Django==3.1.5
django-configurations==2.2
django-haystack==3.0
django-js-asset==1.2.2
django-lti-toolbox==1.0.0b1
django-machina==1.1.4
django-mptt==0.11.0
django-widget-tweaks==1.4.8
pylint==2.6.0
pylint-django==2.4.2
pylint-plugin-utils==0.6
pytest-django==4.1.0
```

**Comment by atodorov** [comment] 2021-01-19 17:21
> Do you know a way to solve this kind of problem that I would have missed ?
> 

Provide a settings file. You can try a dummy one that just doesn't cause Django to crash or you can use django-configurations and try exporting your actual settings as a before step in your CI/test environment.

**Comment by atodorov** [comment] 2021-01-19 17:22
Duplicate of #306

**Closed by atodorov** 2021-01-19 17:21 UTC
