### ISSUE TITLE
Instance of 'list' has no 'first' member

### ISSUE THREAD

**Issue by cristianocca** [PyCQA/pylint-django#174] opened 2018-07-09 17:31 UTC
Python 3.6.6 (also 2.7.14)
pylint 1.9.2
pylint-django 0.11.1

Getting the title error on lines such as
`user = User.objects.filter(email=data['email']).first()`

Wasn't happening before, I can't tell what was the previous version since I only noticed this after re-creating a new virtualenv.

Any ideas? Is this only happening to me?

**Comment by ngtvspc** [comment] 2018-07-09 20:51
@cristianocca I think this is a duplicate of: https://github.com/PyCQA/pylint-django/issues/165

But no, you're not the only one who's seeing this

**Comment by atodorov** [comment] 2018-07-10 06:39
Yes, duplicate of #165

**Closed by atodorov** 2018-07-10 06:39 UTC
