### ISSUE TITLE
QuerySet is inferred as list 

### ISSUE THREAD

**Issue by matsui-goga** [PyCQA/pylint-django#165] opened 2018-06-13 10:10 UTC
If you define the `objects` attribute of a model as `models.Manager()`, you get error
```
E:  5, 3: Instance of 'list' has no 'exists' member (no-member)
```
on
```python
q = AModel.objects.filter(...)
if q.exists():
   ...
```

I'm using pylint 1.9.1, pylint-django 0.11.1.

**Comment by mahmoud** [comment] 2018-06-27 19:04
Is this not a Manager getting inferred as a list? In any case, yes, I'm seeing this a lot:

```
Instance of 'list' has no 'prefetch_related' member
Instance of 'list' has no 'exclude' member
Instance of 'list' has no 'filter' member
Instance of 'list' has no 'aggregate' member
```

And myriad others. Will try and take a look, see how this can be fixed. Also, on the same versions as above.

**Comment by atodorov** [comment] 2018-07-02 11:00
```
q = AModel.objects.filter(...)
if q.exists():
```

The problem comes from the second line. In this example `q` is inferred as list and then you get failures.

pylint-django uses transformations which try to teach it what type an object/attribute is and what other attributes there are.

For this to be resolved effectively we need to teach pylint-django about all Manager methods that return a QuerySet.

@carlio ^^^ not sure what I'm getting myself into with this proposition. Ideas ?

**Comment by carlio** [comment] 2018-07-02 11:16
@atodorov well pylint-django is already a huge shim and things like this exist: https://github.com/PyCQA/pylint-django/blob/master/pylint_django/augmentations/__init__.py#L37 and also https://github.com/PyCQA/pylint-django/blob/master/pylint_django/transforms/fields.py#L31

The whole thing is about second-guessing Django metaprogramming to fit into pylint's expectation of what things are.

So what you're getting yourself into is: adding more special cases to lots of special cases because that's really all that can be done!

**Comment by mahmoud** [comment] 2018-07-10 20:07
Just a heads up that I'm co-working with @ngtvspc on #175 as a fix for this, and invite anyone with expertise/advice to comment there.

**Comment by ajl7** [comment] 2018-07-23 10:23
The problem seems to be caused by a transform in pylint-django that substitutes a Manager by something that returns a list for all the methods that return QuerySets: all(), filter(), etc. This doesn't allow for the same methods on the QuerySet itself, so it doesn't recognise chaining, e.g. MyModel.objects.filter(...).select_related(...).order_by(...) 
If you replace transforms/transforms/django_db_models.py by the attached version, the errors disappear. I don’t know enough about pylint and pylint-django to know if this is an optimal or correct solution, but it seems to work for me. Maybe a test case for chaining such as the example above should be added?
Note that as well as the attached django_db_models.py, I also added ‘QuerySet’ to the _add_transform(‘django.db.models’,’Model’,’Manager’) call in transforms/__init__py
I hope this is helpful.
[django_db_models.py.txt](https://github.com/PyCQA/pylint-django/files/2218899/django_db_models.py.txt)

**Comment by atodorov** [comment] 2018-07-25 14:49
Can you retry with pylint-django 2.0 that was released today ?

**Comment by carlio** [comment] 2018-07-26 09:39
@matsui-goga the problem is that the latest pylint and django don't support 2.7 either so there's no point in pylint-django supporting it. Old versions of all 3 still do though.

**Closed** 2018-07-26 09:39 UTC
