### ISSUE TITLE
Custom error code for not loaded related model

### ISSUE THREAD

**Issue by dmytrokyrychuk** [PyCQA/pylint-django#198] opened 2018-09-25 10:53 UTC
In my opinion `Instance of 'ForeignKey' has no '..' member` errors that show up on ForeignKeys that referend models with a string path is not an issue with `pylint_django` plugin, but rather with the code that is being checked. It is better to communicate this to the plugin users via an error message tied directly to the ForeignKey, rather than via the plugin documentation.

When a model that is referenced by `'app_name.ModelName'` string is not loaded when `pylint_django` inspect a model class, it should produce a new error (e.g., `E5102: Referenced model 'app_name.ModelName' not loaded.`). This way it will be much clearer to the user what is the issue with the code that they wrote. If the user need the circular dependency there, they would be able to disable the error by adding `# pylint: disable=E5102` to the line where ForeignKey is defined.

It would be great if `no-member` errors related to that ForeignKey were suppressed by `pylint_django`, so that if the user would only need to suppress the original `E5102` error on the line where ForeignKey is defined, instead of on every line where it is referenced. Does anyone know if it is possible to suppress errors like this in pylint?

**Comment by atodorov** [comment] 2018-12-14 13:31
@carlio again another one related to #188 and #192. I'm really wondering if we should try to load Django before doing anything else in the hope that all of these references and auto-magical attributes will get resolved. Maybe I will give it a try and see how it goes.

**Comment by carlio** [comment] 2019-04-23 22:01
@atodorov I missed this reference my apologies.

Originally Django was not loaded because any importing of `django.db.models` resulted in settings being loaded and it would fail due to settings not being properly configured.

However that was many Django versions ago and it could be the case that the range of Django versions supported now do not have this problem (https://docs.djangoproject.com/en/2.2/topics/settings/#using-settings-without-setting-django-settings-module) so loading Django might not immediately cause breakage any more.

**Comment by carlio** [comment] 2019-04-23 22:02
It could however lead to default settings that impact the code people are using pyling-django to check, so to avoid that I think leaving this as pure linting rather than depending on Django would make things easier and less brittle.

**Comment by atodorov** [comment] 2019-04-26 09:43
With the changes from #229 merged I think the original root cause of this issue has been resolved.

IMO there is no need to add a custom error message anymore and no need trying to load django settings (for now :)).

As @imomaliev suggested in #229:
> close until another issues related to this emerge.

@carlio, @dmytrokyrychuk what do you think ?

**Comment by carlio** [comment] 2019-04-26 09:45
@atodorov I say close it and if it isn't fixed, we can reopen or create a new issue.

**Closed** 2019-04-26 10:00 UTC
