### ISSUE TITLE
crash with DecimalField

### ISSUE THREAD

**Issue by craynic** [PyCQA/pylint-django#221] opened 2019-02-28 05:25 UTC
system: Archlinux 4.20.7-arch1-1-ARCH
Python 3.7.2
pylint==2.3.0
pylint-django==2.0.6
pylint-plugin-utils==0.5
astroid==2.2.0
Django==2.1.7

my model:

    class Payment(models.Model):
        id = models.UUIDField(default=uuid.uuid4, primary_key=True, editable=False)
        amount = models.DecimalField(max_digits=12, decimal_places=2)
        some fields else...

error:

> pylint --load-plugins pylint_django  boss_billing.models -d R,C
Traceback (most recent call last):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/__init__.py", line 81, in _inference_tip_cached
    return iter(_cache[func, node])
KeyError: (<function apply_type_shim at 0x7fcbf52936a8>, <ClassDef.DecimalField l.1443 at 0x7fcbf42ba9e8>)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/manager.py", line 119, in ast_from_module_name
    module = modutils.load_module_from_name(modname)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/modutils.py", line 183, in load_module_from_name
    return load_module_from_modpath(dotted_name.split('.'), path, use_sys)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/modutils.py", line 226, in load_module_from_modpath
    module = imp.load_module(curname, mp_file, mp_filename, mp_desc)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: libmpdec.so.2: cannot open shared object file: No such file or directory
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
  File "/home/craynic/.virtualenvs/boss/bin/pylint", line 10, in <module>
    sys.exit(run_pylint())
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/__init__.py", line 20, in run_pylint
    Run(sys.argv[1:])
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/lint.py", line 1608, in __init__
    linter.check(args)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/lint.py", line 938, in check
    self._do_check(files_or_modules)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/lint.py", line 1071, in _do_check
    self.check_astroid_module(ast_node, walker, rawcheckers, tokencheckers)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/lint.py", line 1154, in check_astroid_module
    walker.walk(ast_node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/utils.py", line 1269, in walk
    self.walk(child)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/utils.py", line 1266, in walk
    cb(astroid)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 57, in augment_func
    augmentation(chain, node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 148, in do_suppress
    chain()
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_plugin_utils/__init__.py", line 56, in chain
    old_method(node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/checkers/classes.py", line 729, in visit_classdef
    self._check_bases_classes(node)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/checkers/classes.py", line 1444, in _check_bases_classes
    unimplemented_abstract_methods(node, is_abstract).items(),
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/checkers/utils.py", line 792, in unimplemented_abstract_methods
    infered = safe_infer(obj)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint/checkers/utils.py", line 1073, in safe_infer
    value = next(inferit)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 84, in wrapped
    res = next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/bases.py", line 113, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/util.py", line 144, in limit_inference
    yield from islice(iterator, size)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/context.py", line 103, in cache_generator
    for result in generator:
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 123, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 84, in wrapped
    res = next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/inference.py", line 189, in infer_call
    for callee in self.func.infer(context):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/util.py", line 144, in limit_inference
    yield from islice(iterator, size)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/context.py", line 103, in cache_generator
    for result in generator:
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 84, in wrapped
    res = next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 123, in raise_if_nothing_inferred
    yield next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/inference.py", line 293, in infer_attribute
    yield from owner.igetattr(self.attrname, context)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/bases.py", line 113, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/util.py", line 144, in limit_inference
    yield from islice(iterator, size)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/context.py", line 103, in cache_generator
    for result in generator:
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 84, in wrapped
    res = next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/bases.py", line 113, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/util.py", line 144, in limit_inference
    yield from islice(iterator, size)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/context.py", line 103, in cache_generator
    for result in generator:
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/decorators.py", line 84, in wrapped
    res = next(generator)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/bases.py", line 113, in _infer_stmts
    for inferred in stmt.infer(context=context):
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/node_classes.py", line 309, in infer
    return self._explicit_inference(self, context, **kwargs)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/__init__.py", line 83, in _inference_tip_cached
    result = func(*args, **kwargs)
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/pylint_django/transforms/fields.py", line 44, in apply_type_shim
    base_nodes = MANAGER.ast_from_module_name('_decimal').lookup('Decimal')
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/manager.py", line 147, in ast_from_module_name
    raise e
  File "/home/craynic/.virtualenvs/boss/lib/python3.7/site-packages/astroid/manager.py", line 123, in ast_from_module_name
    modname=modname, path=found_spec.location) from ex
astroid.exceptions.AstroidImportError: <exception str() failed>

**Comment by craynic** [comment] 2019-02-28 05:26
#219 may be related.
`base_nodes = MANAGER.ast_from_module_name('decimal').lookup('Decimal')` this line works for me.

**Comment by atodorov** [comment] 2019-04-11 07:27
I see you are using Python 3.7.2 while in Travis we have 3.7.1. I am trying to bump the versions we use for testing or at least figure out what causes the failures because until we are able to reproduce reliably we can't test and merge the fixes proposed in #219.

**Comment by atodorov** [comment] 2019-04-11 08:10
@craynic, @fadedDexofan

I'm not seeing this crash with Python 3.7.3 (3.7-dev in CI) in 
https://github.com/PyCQA/pylint-django/pull/225

Try upgrading your astroid/pylint/pylint-django versions and let us know if you are able to reproduce and how exacty. Otherwise there's nothing we can do about it.

**Comment by fadedDexofan** [comment] 2019-04-11 08:29
![image](https://user-images.githubusercontent.com/4462103/55942253-5cdf7700-5c87-11e9-99cd-44874ad97b55.png)
I'm using latest Arch Linux Python in venv.
This also works 
![image](https://user-images.githubusercontent.com/4462103/55942302-75e82800-5c87-11e9-8a07-bff65945152e.png)
but default not
![image](https://user-images.githubusercontent.com/4462103/55942331-87313480-5c87-11e9-825f-ef641da3cc0d.png)
It produce a long stacktrace that end's with 
![image](https://user-images.githubusercontent.com/4462103/55942453-c069a480-5c87-11e9-9f26-b0581790d521.png)

**Comment by atodorov** [comment] 2019-04-11 13:16
@fadedDexofan thanks for the details. Not sure if any of us has Arch Linux, Travis CI is Ubuntu based and I'm using RHEL. Both of these as far as I know have `_decimal` and not `_pydecimal`. If you can find out what is `_pydecimal` and where it comes from and why Arch uses that instead of `_decimal` I will try to create a reproducer.


What is the actual Python compiler in Arch? Is it CPython ?

(next time please copy the actual text, not images)

**Comment by atodorov** [comment] 2019-04-16 09:16
Closed in #219 (missing the Fixes keyword)

**Closed by atodorov** 2019-04-16 09:16 UTC

**Comment by craynic** [comment] 2019-05-16 04:31
I think I've found what `_pydecimal` is.
In cpython, `import decimal` will try import from `_decimal` first. if it does not exist, `_pydeciaml` will be used. `_pydecimal` is a pure-python implementation for decimal(https://github.com/python/cpython/blob/3.7/Lib/_pydecimal.py), acts as a fallback implementation, while `_decimal` is a wrapper for `libmpdec`(https://github.com/python/cpython/tree/3.7/Modules/_decimal), with better performance.
In Archlinux Python build script, `mpdecimal` is an optional dependency, which means it may not be installed during compiling, cause the lack of `_decimal`.
In my opinion, we should not assume all the python executable come with `_decimal` built in. `_pydecimal` may be better to do the job.
