### ISSUE TITLE
Integrated GIT in visual code-insiders

### ISSUE THREAD

**Issue by 70-6C-65-61-73-75-72-65h** [PyCQA/pylint-django#226] opened 2019-04-13 09:54 UTC
I have a really weird problem, the solution of which I have not found on the Internet.
When I open console GIT Bash I could see the next status of my changes(pic 1).  
![pic1](https://user-images.githubusercontent.com/37050156/56077981-33d7f700-5deb-11e9-8d2e-b95ae59ae086.png)

But in integrated GIT within code-insiders I can’t see this changes(pic 2).
 
![pic2](https://user-images.githubusercontent.com/37050156/56077985-43efd680-5deb-11e9-8e6d-78ff3ca0e374.png)

When I staged all changes in code-insiders extention all work properly, but I havent any changes yet, and moreover, I never saw any changes in this integrated GIT, but in console GIT Bash I can see(pic 3). 
![pic3](https://user-images.githubusercontent.com/37050156/56077993-4baf7b00-5deb-11e9-8b65-f6c8c7ecfcd6.png)

Can me anyone explain where my fault is?

**Comment by carlio** [comment] 2019-04-13 09:57
One fault is that this has nothing to do with pylint-django - closing issue as not a bug

**Closed by carlio** 2019-04-13 09:57 UTC
